version: '3'

services:
  harold-fit-app:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    image: harold-fit-docker
    container_name: harold-fit-app
    restart: "no"
    ports:
      - "${PORT}:${PORT}"
    environment:
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_USERNAME: ${DB_USERNAME}
      PORT: ${PORT}
      HOST_API: ${HOST_API}
      JWT_SECRET: ${JWT_SECRET}

  db:
    image: postgres:16.1
    restart: "no"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: haroldfitdb
    volumes:
      - ./postgres:/var/lib/postgresql/data